version: 2

run:
  timeout: 5m

linters-settings:
  errcheck:
    check-type-assertions: true

linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - staticcheck

issues:
  exclude-rules:
    - path: _test\.go$
      text: "Using the variable on range scope"
